import anthropic
import os
import re
from datetime import date
from pathlib import Path

# ── Topics pool (rotates so content stays fresh) ──────────────────────────────
TOPICS = [
    "Async/Await patterns and event loops",
    "Graph algorithms and real-world applications",
    "REST vs GraphQL vs gRPC",
    "Docker containerization best practices",
    "Design patterns: Observer and Publisher/Subscriber",
    "Database indexing strategies",
    "OAuth 2.0 and JWT authentication flows",
    "Functional programming concepts",
    "Memory management and garbage collection",
    "Microservices communication patterns",
    "WebSockets and real-time data",
    "SOLID principles with examples",
    "Caching strategies (Redis, CDN, in-memory)",
    "CI/CD pipeline design",
    "API rate limiting and throttling",
    "Recursion vs iteration tradeoffs",
    "Binary search and divide-and-conquer",
    "CSS Grid and Flexbox layouts",
    "TypeScript advanced types and generics",
    "Serverless architecture patterns",
    "Data serialization: JSON vs MessagePack vs Protobuf",
    "Web security: XSS, CSRF, SQL injection",
    "Concurrency models: threads, goroutines, async",
    "Monorepo vs polyrepo structure",
    "LLM prompt engineering techniques",
    "Vector databases and semantic search",
    "Kubernetes basics for developers",
    "Event-driven architecture",
    "Test-driven development strategies",
    "HTTP/2 and HTTP/3 improvements",
    "Regular expressions deep dive",
    "Shell scripting productivity tips",
    "Git internals and advanced workflows",
    "WebAssembly use cases",
    "Progressive Web Apps (PWA)",
    "Machine learning feature engineering",
    "Data pipelines with Python",
    "Browser rendering performance",
    "Distributed systems: CAP theorem",
    "Blockchain fundamentals for developers",
    "Dependency injection patterns",
    "API versioning strategies",
    "Code review best practices",
    "System design: URL shortener",
    "System design: rate limiter",
    "Observability: logs, metrics, traces",
    "Zero-downtime deployments",
    "Idempotency in API design",
    "Backpressure and flow control",
    "Finite state machines in software",
]

PROMPT_TEMPLATE = """
You are a senior software engineer writing a daily developer insight post for GitHub.

Today's topic: **{topic}**
Date: {today}

Write a comprehensive, engaging markdown document covering this topic.
Structure it EXACTLY as follows (use these exact headings):

# 📌 {topic}
*{today} · Daily Dev Insight*

## 🧠 Overview
(2-3 paragraphs explaining the concept clearly. Be insightful, not just definitional.)

## 💡 Key Concepts
(3-5 bullet points with the most important ideas to understand)

## 🐍 Python Example
(A real, runnable Python code example with inline comments. Use ```python fences.)

## 🟨 JavaScript Example
(A real, runnable JavaScript/Node.js code example with inline comments. Use ```javascript fences.)

## ⚖️ When To Use / When To Avoid
(A short table or bullet list comparing when this is a good fit vs a bad fit)

## 📚 Further Reading
(3-5 bullet points with descriptive link text — use realistic URLs like MDN, docs.python.org, etc.)

---
*Auto-generated by [Daily Dev Insights Bot](https://github.com) · Powered by Claude AI*

Rules:
- Make the code examples genuinely useful and non-trivial (20-40 lines each)
- Be opinionated and practical — give real engineering advice
- Keep the tone conversational but professional
- Total length: 600-900 words
"""

def pick_topic(today: date) -> str:
    day_index = today.timetuple().tm_yday
    return TOPICS[day_index % len(TOPICS)]

def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"\s+", "-", text.strip())
    return text

def generate_insight(topic: str, today: date) -> str:
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    prompt = PROMPT_TEMPLATE.format(topic=topic, today=today.strftime("%B %d, %Y"))

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text

def update_readme(insights_dir: Path, today: date, topic: str, filename: str):
    readme_path = Path("README.md")
    recent_files = sorted(insights_dir.glob("*.md"), reverse=True)[:5]

    recent_links = "\n".join(
        f"- [{f.stem}](insights/{f.name})" for f in recent_files
    )

    readme_content = f"""# 📚 Daily Dev Insights

> Auto-generated daily developer insights covering algorithms, system design,
> best practices, and modern engineering topics — powered by Claude AI.

## ✨ Latest Insight

**[{topic}](insights/{filename})** · {today.strftime("%B %d, %Y")}

## 📅 Recent Posts

{recent_links}

## 🚀 About

This repository updates automatically every day via GitHub Actions.
Each post includes:
- 🧠 Concept overview
- 🐍 Python code example
- 🟨 JavaScript code example
- ⚖️ When to use / avoid
- 📚 Further reading

*Powered by [Anthropic Claude](https://anthropic.com)*
"""
    readme_path.write_text(readme_content)
    print(f"✅ README.md updated")

def main():
    today = date.today()
    topic = pick_topic(today)
    slug = slugify(topic)
    filename = f"{today.isoformat()}-{slug}.md"

    insights_dir = Path("insights")
    insights_dir.mkdir(exist_ok=True)

    output_path = insights_dir / filename

    print(f"📝 Generating insight for: {topic}")
    content = generate_insight(topic, today)

    output_path.write_text(content)
    print(f"✅ Saved: {output_path}")

    update_readme(insights_dir, today, topic, filename)

if __name__ == "__main__":
    main()
